return {
	-- "stevedylandev/darkmatter-nvim",
	-- lazy = false,
	-- priority = 1000,
	-- config = function()
	-- 	vim.cmd("colorscheme darkmatter")
	-- 	-- set custom background color
	-- 	-- vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
	-- 	-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE" })
	-- 	-- vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE" })
	-- 	-- vim.api.nvim_set_hl(0, "StatusLine", { bg = "NONE" })
	-- 	-- Improve comment readability
	-- 	vim.api.nvim_set_hl(0, "Comment", { fg = "#6b7280", italic = true })
	-- 	-- Treesitter comments (important)
	-- 	vim.api.nvim_set_hl(0, "@comment", { fg = "#6b7280", italic = true })
	-- end,

	"cranberry-clockworks/coal.nvim",
	lazy = false,
	config = function()
		require("coal").setup({
			colors = {
				smoky_black = "#000000",
			},
		})
		vim.cmd("colorscheme coal")
	end,

	-- "metalelf0/black-metal-theme-neovim",
	-- lazy = false,
	-- priority = 1000,
	-- config = function()
	-- 	require("black-metal").setup({
	-- 		-----MAIN OPTIONS-----
	-- 		--
	-- 		-- Can be one of: bathory | burzum | dark-funeral | darkthrone | emperor | gorgoroth | immortal | impaled-nazarene | khold | marduk | mayhem | nile | taake | thyrfing | venom | windir
	-- 		theme = "bathory",
	-- 		-- Can be one of: 'light' | 'dark', or set via vim.o.background
	-- 		variant = "dark",
	-- 		-- Use an alternate, lighter bg
	-- 		alt_bg = false,
	-- 		-- If true, docstrings will be highlighted like strings, otherwise they will be
	-- 		-- highlighted like comments. Note, behavior is dependent on the language server.
	-- 		colored_docstrings = true,
	-- 		-- If true, highlights the {sign,fold} column the same as cursorline
	-- 		cursorline_gutter = true,
	-- 		-- If true, highlights the gutter darker than the bg
	-- 		dark_gutter = false,
	-- 		-- if true favor treesitter highlights over semantic highlights
	-- 		favor_treesitter_hl = false,
	-- 		-- Don't set background of floating windows. Recommended for when using floating
	-- 		-- windows with borders.
	-- 		plain_float = false,
	-- 		-- Show the end-of-buffer character
	-- 		show_eob = true,
	-- 		-- If true, enable the vim terminal colors
	-- 		term_colors = true,
	-- 		-- Keymap (in normal mode) to toggle between light and dark variants.
	-- 		toggle_variant_key = nil,
	-- 		-- Don't set background
	-- 		transparent = false,
	-- 		-----DIAGNOSTICS and CODE STYLE-----
	-- 		--
	-- 		diagnostics = {
	-- 			darker = true, -- Darker colors for diagnostic
	-- 			undercurl = true, -- Use undercurl for diagnostics
	-- 			background = true, -- Use background color for virtual text
	-- 		},
	-- 		-- The following table accepts values the same as the `gui` option for normal
	-- 		-- highlights. For example, `bold`, `italic`, `underline`, `none`.
	-- 		code_style = {
	-- 			comments = "italic",
	-- 			conditionals = "none",
	-- 			functions = "none",
	-- 			keywords = "none",
	-- 			headings = "bold", -- Markdown headings
	-- 			operators = "none",
	-- 			keyword_return = "none",
	-- 			strings = "none",
	-- 			variables = "none",
	-- 		},
	-- 		-----PLUGINS-----
	-- 		--
	-- 		-- The following options allow for more control over some plugin appearances.
	-- 		plugin = {
	-- 			lualine = {
	-- 				-- Bold lualine_a sections
	-- 				bold = true,
	-- 				-- Don't set section/component backgrounds. Recommended to not set
	-- 				-- section/component separators.
	-- 				plain = false,
	-- 			},
	-- 			cmp = { -- works for nvim.cmp and blink.nvim
	-- 				-- Don't highlight lsp-kind items. Only the current selection will be highlighted.
	-- 				plain = false,
	-- 				-- Reverse lsp-kind items' highlights in blink/cmp menu.
	-- 				reverse = false,
	-- 			},
	-- 		},
	-- 		-- CUSTOM HIGHLIGHTS --
	-- 		--
	-- 		-- Override default colors
	-- 		colors = {},
	-- 		-- Override highlight groups
	-- 		highlights = {},
	-- 	})
	-- 	-- Convenience function that simply calls `:colorscheme <theme>` with the theme
	-- 	-- specified in your config.
	-- 	require("black-metal").load()
	-- end,

	-- "rose-pine/neovim",
	-- name = "rose-pine",
	-- config = function()
	-- 	require("rose-pine").setup({
	-- 		variant = "auto", -- auto, main, moon, or dawn
	-- 		dark_variant = "main", -- main, moon, or dawn
	-- 		dim_inactive_windows = false,
	-- 		extend_background_behind_borders = true,
	--
	-- 		enable = {
	-- 			terminal = true,
	-- 			legacy_highlights = true, -- Improve compatibility for previous versions of Neovim
	-- 			migrations = true, -- Handle deprecated options automatically
	-- 		},
	--
	-- 		styles = {
	-- 			bold = true,
	-- 			italic = true,
	-- 			transparency = true,
	-- 		},
	--
	-- 		groups = {
	-- 			border = "muted",
	-- 			link = "iris",
	-- 			panel = "surface",
	--
	-- 			error = "love",
	-- 			hint = "iris",
	-- 			info = "foam",
	-- 			note = "pine",
	-- 			todo = "rose",
	-- 			warn = "gold",
	--
	-- 			git_add = "foam",
	-- 			git_change = "rose",
	-- 			git_delete = "love",
	-- 			git_dirty = "rose",
	-- 			git_ignore = "muted",
	-- 			git_merge = "iris",
	-- 			git_rename = "pine",
	-- 			git_stage = "iris",
	-- 			git_text = "rose",
	-- 			git_untracked = "subtle",
	--
	-- 			h1 = "iris",
	-- 			h2 = "foam",
	-- 			h3 = "rose",
	-- 			h4 = "gold",
	-- 			h5 = "pine",
	-- 			h6 = "foam",
	-- 		},
	--
	-- 		palette = {},
	--
	-- 		-- NOTE: Highlight groups are extended (merged) by default. Disable this
	-- 		-- per group via `inherit = false`
	-- 		highlight_groups = {},
	-- 	})
	--
	-- 	vim.cmd("colorscheme rose-pine")
	-- 	-- vim.cmd("colorscheme rose-pine-main")
	-- 	-- vim.cmd("colorscheme rose-pine-moon")
	-- 	-- vim.cmd("colorscheme rose-pine-dawn")
	-- end,
}
