local now, later = MiniDeps.now, MiniDeps.later

now(function()
	require("plugins.colorscheme")
end)

later(function()
	require("plugins.local")
	require("plugins.mini")
	require("plugins.mason")
	require("plugins.dap")
	require("plugins.conform")
	require("plugins.lint")
	require("litee.lib").setup()
	require("litee.gh").setup()
	require("colorizer").setup()
end)

later(function()
	require("plugins.treesitter")
	require("plugins.blink")
	require("plugins.copilot")
	require("plugins.org")
	require("plugins.marks")
	require("plugins.kulala")
end)
