require("plugins.colorscheme")
require("plugins.picker")
require("plugins.dap")
require("plugins.conform")
require("plugins.lint")
require("plugins.vim")
require("plugins.treesitter")
require("plugins.org")
-- require("plugins.kulala")
